package enums;

import java.util.ArrayList;
import java.util.List;


/**
 * @deprecated ClubEnum will be removed soon and replaced with class {@link GameObjects.Club}.
 */
@Deprecated
public enum ClubEnum {
    RETIRED("Retired", LeagueEnum.RETIRED),
    WITHOUT_CLUB("Without club", LeagueEnum.WITHOUT_CLUB),

    MAN_CITY("Manchester City", LeagueEnum.ENG_1),
    ARSENAL("FC Arsenal", LeagueEnum.ENG_1),
    CHELSEA("FC Chelsea", LeagueEnum.ENG_1),
    LIVERPOOL("FC Liverpool", LeagueEnum.ENG_1),
    MAN_UTD("Manchester United", LeagueEnum.ENG_1),
    SPURS("Tottenham Hotspur", LeagueEnum.ENG_1),
    NEWCASTLE("Newcastle United", LeagueEnum.ENG_1),
    ASTON_VILLA("Aston Villa", LeagueEnum.ENG_1),
    BRIGHTON("Brighton & Hove Albion", LeagueEnum.ENG_1),
    WESTHAM("West Ham United", LeagueEnum.ENG_1),
    BRENTFORD("FC Brentford", LeagueEnum.ENG_1),
    NHAM_FOREST("Nottingham Forest", LeagueEnum.ENG_1),
    CRYSTAL_PALACE("Crystal Palace", LeagueEnum.ENG_1),
    EVERTON("FC Everton", LeagueEnum.ENG_1),
    BOURNEMOUTH("AFC Bournemouth", LeagueEnum.ENG_1),
    WOLVES("Wolverhampton Wanderers", LeagueEnum.ENG_1),
    FULHAM("FC Fulham", LeagueEnum.ENG_1),
    BURNLEY("FC Burnley", LeagueEnum.ENG_1),
    SHEFFIELD_UTD("Sheffield United", LeagueEnum.ENG_1),
    LUTON("Luton Town", LeagueEnum.ENG_1),

    LEICESTER("Leicester City", LeagueEnum.ENG_2),
    SOUTHAMPTON("FC Southampton", LeagueEnum.ENG_2),
    LEEDS("Leeds United", LeagueEnum.ENG_2),
    SUNDERLAND("AFC Sunderland", LeagueEnum.ENG_2),
    HULL_CITY("Hull City", LeagueEnum.ENG_2),
    MIDDLESBROUGH("FC Middlesbrough", LeagueEnum.ENG_2),
    NORWICH("Norwich City", LeagueEnum.ENG_2),
    BLACKBURN("Blackburn Rovers", LeagueEnum.ENG_2),
    SWANSEA("Swansea City", LeagueEnum.ENG_2),
    WATFORD("FC Watford", LeagueEnum.ENG_2),
    STOKE("Stoke City", LeagueEnum.ENG_2),
    WEST_BROM("West Bromwich Albion", LeagueEnum.ENG_2),
    COVENTRY("Coventry City", LeagueEnum.ENG_2),
    BIRMINGHAM("Birmingham City", LeagueEnum.ENG_2),
    IPSWICH("Ipswich Town", LeagueEnum.ENG_2),
    CARDIFF("Cardiff City", LeagueEnum.ENG_2),
    PRESTON_NE("Preston North End", LeagueEnum.ENG_2),
    MILLWALL("FC Millwall", LeagueEnum.ENG_2),
    BRISTOL("Bristol City", LeagueEnum.ENG_2),
    HUDDERSFIELD("Huddersfield Town", LeagueEnum.ENG_2),
    QUEENS_PR("Queens Park Rangers", LeagueEnum.ENG_2),
    PLYMOUTH("Plymouth Argyle", LeagueEnum.ENG_2),
    ROTHERHAM("Rotherham United", LeagueEnum.ENG_2),
    SHEFFIELD_W("Sheffield Wednesday", LeagueEnum.ENG_2),

    PBOROUGH("Peterborough United", LeagueEnum.ENG_3),
    DERBY_COUNTY("Derby County", LeagueEnum.ENG_3),
    BARNSLEY("FC Barnsley", LeagueEnum.ENG_3),
    READING("FC Reading", LeagueEnum.ENG_3),
    BLACKPOOL("FC Blackpool", LeagueEnum.ENG_3),
    CHARLTON("Charlton Athletic", LeagueEnum.ENG_3),
    PORTSMOUTH("FC Portsmouth", LeagueEnum.ENG_3),
    BOLTON("Bolton Wanderers", LeagueEnum.ENG_3),
    WIGAN("Wigan Athletic", LeagueEnum.ENG_3),
    BRISTOL_ROVERS("Bristol Rovers", LeagueEnum.ENG_3),
    OXFORD("Oxford United", LeagueEnum.ENG_3),
    EXETER("Exeter City", LeagueEnum.ENG_3),
    LINCOLN("Lincoln City", LeagueEnum.ENG_3),
    FLEETWOOD("Fleetwood Town", LeagueEnum.ENG_3),
    WYCOMBE("Wycombe Wanderers", LeagueEnum.ENG_3),
    PORT_VALE("FC Port Vale", LeagueEnum.ENG_3),
    STEVENAGE("FC Stevenage", LeagueEnum.ENG_3),
    CARLISLE("Carlisle United", LeagueEnum.ENG_3),
    SHREWSBURY("Shrewsbury Town", LeagueEnum.ENG_3),
    NORTHAMPTON("Northampton Town", LeagueEnum.ENG_3),
    LEYTON("Leyton Orient", LeagueEnum.ENG_3),
    CAMBRIDGE("Cambrige United", LeagueEnum.ENG_3),
    BURTON("Burton Albion", LeagueEnum.ENG_3),
    CHELTENHAM("Cheltenham Town", LeagueEnum.ENG_3),

    WREXHAM("AFC Wrexham", LeagueEnum.ENG_4),
    STOCKPORT("Stockport County", LeagueEnum.ENG_4),
    FOREST_GREEN("Forest Green Rovers", LeagueEnum.ENG_4),
    COLCHESTER("Colchester United", LeagueEnum.ENG_4),
    MK_DONS("Milton Keynes Dons", LeagueEnum.ENG_4),
    CREWE("Crewe Alexandra", LeagueEnum.ENG_4),
    BRADFORD("Bradford City", LeagueEnum.ENG_4),
    GRIMSBY("Grimsby Town", LeagueEnum.ENG_4),
    DONCASTER("Doncaster Rovers", LeagueEnum.ENG_4),
    MANSFIELD("Mansfield", LeagueEnum.ENG_4),
    SALFORD("Salford City", LeagueEnum.ENG_4),
    GILLINGHAM("FC Gillingham", LeagueEnum.ENG_4),
    WALSALL("FC Walsall", LeagueEnum.ENG_4),
    BARROW("AFC Barrow", LeagueEnum.ENG_4),
    WIMBLEDON("AFC Wimbledon", LeagueEnum.ENG_4),
    MORECAMBE("FC Morecambe", LeagueEnum.ENG_4),
    NOTTS_COUNTY("Notts County", LeagueEnum.ENG_4),
    STANLEY("Accrington Stanley", LeagueEnum.ENG_4),
    TRANMERE("Tranmere Rovers", LeagueEnum.ENG_4),
    NEWPORT("Newport County", LeagueEnum.ENG_4),
    SWINDON("Swindon Town", LeagueEnum.ENG_4),
    HARROGATE("Harrogate Town", LeagueEnum.ENG_4),
    SUTTON("Sutton United", LeagueEnum.ENG_4),
    CRAWLEY("Crawley Town", LeagueEnum.ENG_4),

    BAYERN("Bayern München", LeagueEnum.DE_1),
    LEVERKUSEN("Bayer 04 Leverkusen", LeagueEnum.DE_1),
    LEIPZIG("RB Leipzig", LeagueEnum.DE_1),
    BVB("Borussia Dortmund", LeagueEnum.DE_1),
    WOLFSBURG("VfL Wolfsburg", LeagueEnum.DE_1),
    FRANKFURT("Eintracht Frankfurt", LeagueEnum.DE_1),
    STUTTGART("VfB Stuttgart", LeagueEnum.DE_1),
    BORUSSIA_M("Borussia Mönchengladbach", LeagueEnum.DE_1),
    FREIBURG("SC Freiburg", LeagueEnum.DE_1),
    UNION("1.FC Union Berlin", LeagueEnum.DE_1),
    TSG("TSG 1899 Hoffenheim", LeagueEnum.DE_1),
    AUGSBURG("FC Augsburg", LeagueEnum.DE_1),
    MAINZ("FSV Mainz 05", LeagueEnum.DE_1),
    KOLN("1.FC Köln", LeagueEnum.DE_1),
    BREMEN("SV Werder Bremen", LeagueEnum.DE_1),
    BOCHUM("VfL Bochum", LeagueEnum.DE_1),
    HEIDENHEIM("1.FC Heidenheim 1846", LeagueEnum.DE_1),
    DARMSTADT("SV Darmstadt 98", LeagueEnum.DE_1),

    HSV("Hamburger SV", LeagueEnum.DE_2),
    HERTHA("Hertha BSC", LeagueEnum.DE_2),
    DUSSELDORF("Fortuna Düsseldorf", LeagueEnum.DE_2),
    SCHALKE("Schalke 04", LeagueEnum.DE_2),
    NURNBERG("1.FC Nürnberg", LeagueEnum.DE_2),
    HANNOVER("Hannover 96", LeagueEnum.DE_2),
    STPAULI("FC St. Pauli", LeagueEnum.DE_2),
    KIEL("Holstein Kiel", LeagueEnum.DE_2),
    FURTH("SpVgg Greuther Fürth", LeagueEnum.DE_2),
    KAISERSLAUTERN("1.FC Kaiserslautern", LeagueEnum.DE_2),
    PADERBORN("SC Paderborn 07", LeagueEnum.DE_2),
    ELVERSBERG("SV 07 Elversberg", LeagueEnum.DE_2),
    MAGDEBURG("1.FC Magdeburg", LeagueEnum.DE_2),
    KSC("Karlsruher SC", LeagueEnum.DE_2),
    WIESBADEN("SV Wehen Wiesbaden", LeagueEnum.DE_2),
    ROSTOCK("FC Hansa Rostock", LeagueEnum.DE_2),
    OSNABRUCK("VfL Osnabrück", LeagueEnum.DE_2),
    BRAUNSCHWEIG("Eintracht Braunschweig", LeagueEnum.DE_2),

    BVB_II("Borussia Dortmund II", LeagueEnum.DE_3),
    DYNAMO_DRESDEN("SG Dynamo Dresden", LeagueEnum.DE_3),
    FREIBURG_II("SC Freiburg II", LeagueEnum.DE_3),
    SANDHAUSEN("SV Sandhausen", LeagueEnum.DE_3),
    INGOLSTADT("FC Ingolstadt 04", LeagueEnum.DE_3),
    DUISBURG("MSV Duisburg", LeagueEnum.DE_3),
    REGENSBURG("SSV Jahn Regensburg", LeagueEnum.DE_3),
    BIELEFELD("Arminia Bielefeld", LeagueEnum.DE_3),
    SAARBRUCKEN("1.FC Saarbrücken", LeagueEnum.DE_3),
    HALLESCHER("Hallescher FC", LeagueEnum.DE_3),
    MUNICH_1860("TSV 1860 München", LeagueEnum.DE_3),
    MANNHEIM("SV Waldhof Mannheim", LeagueEnum.DE_3),
    VIKTORIA_KOLN("FC Viktoria Köln", LeagueEnum.DE_3),
    RW_ESSEN("Rot-Weiss Essen", LeagueEnum.DE_3),
    PREUSSEN("Preußen Münster", LeagueEnum.DE_3),
    VERL("SC Verl", LeagueEnum.DE_3),
    ERZGEBIRGE("FC Erzgebirge Aue", LeagueEnum.DE_3),
    ULM("SSV Ulm 1846", LeagueEnum.DE_3),
    UNTERHACHING("SpVgg Unterhaching", LeagueEnum.DE_3),
    LUBECK("VfB Lübeck", LeagueEnum.DE_3),

    VIKTORIA_BERLIN("FC Viktoria 1889 Berlin", LeagueEnum.DE_4),

    REAL_MADRID("Real Madrid", LeagueEnum.ES_1),
    BARCA("FC Barcelona", LeagueEnum.ES_1),
    SOCIEDAD("Real Sociedad", LeagueEnum.ES_1),
    ATLETICO("Atlético Madrid", LeagueEnum.ES_1),
    ATHLETIC("Athletic Bilbao", LeagueEnum.ES_1),
    GIRONA("FC Girona", LeagueEnum.ES_1),
    VILLARREAL("FC Villarreal", LeagueEnum.ES_1),
    BETIS("Real Betis", LeagueEnum.ES_1),
    VALENCIA("FC Valencia", LeagueEnum.ES_1),
    SEVILLA("FC Sevilla", LeagueEnum.ES_1),
    GETAFE("FC Getafe", LeagueEnum.ES_1),
    OSASUNA("CD Osasuna", LeagueEnum.ES_1),
    CELTA("Celta Vigo", LeagueEnum.ES_1),
    ALMERIA("UD Almería", LeagueEnum.ES_1),
    MALLORCA("RCD Mallorca", LeagueEnum.ES_1),
    GRANADA("FC Granada", LeagueEnum.ES_1),
    RAYO("Rayo Vallecano", LeagueEnum.ES_1),
    ALAVES("Deportivo Alavés", LeagueEnum.ES_1),
    LAS_PALMAS("UD Las Palmas", LeagueEnum.ES_1),
    CADIZ("FC Cádiz", LeagueEnum.ES_1),

    ESPANYOL("Espanyol", LeagueEnum.ES_2),
    VALLADOLID("Real Valladolid", LeagueEnum.ES_2),
    SARAGOSSA("Real Saragossa", LeagueEnum.ES_2),
    ELCHE("FC Elche", LeagueEnum.ES_2),
    OVIEDO("Real Oviedo", LeagueEnum.ES_2),
    GIJON("Sporting Gijón", LeagueEnum.ES_2),
    EIBAR("SD Eibar", LeagueEnum.ES_2),
    LEVANTE("UD Levante", LeagueEnum.ES_2),
    LEGANES("CD Leganés", LeagueEnum.ES_2),
    VILLARREAL_B("FC Villarreal B", LeagueEnum.ES_2),
    ANDORRA("FC Andorra", LeagueEnum.ES_2),
    TENERIFFA("CD Teneriffa", LeagueEnum.ES_2),
    RACING("Racing Santander", LeagueEnum.ES_2),
    HUESCA("SD Huesca", LeagueEnum.ES_2),
    ALBACETE("Albacete Balompié", LeagueEnum.ES_2),
    MIRANDES("CD Mirandés", LeagueEnum.ES_2),
    BURGOS("Burgos CF", LeagueEnum.ES_2),
    CARTAGENA("FC Cartagena", LeagueEnum.ES_2),
    FERROL("Racing Ferrol", LeagueEnum.ES_2),
    ELDENSE("CD Eldense", LeagueEnum.ES_2),
    ALCORCON("AD Alcorcón", LeagueEnum.ES_2),
    AMOREBIETA("SD Amorebieta", LeagueEnum.ES_2),

    ANTONIANO("Club Atlético Antoniano", LeagueEnum.ES_4),

    BRENO("USD Breno", LeagueEnum.IT_4),

    FORFAR("Forfar Athletic FC", LeagueEnum.SCO_2),

    KEITH("Keith FC", LeagueEnum.SCO_5),

    DUNDALK("Dundalk FC", LeagueEnum.IE_1),

    VIANENSE("SC Vianense", LeagueEnum.PT_3),

    DEN_BOSCH("FC Den Bosch", LeagueEnum.NL_2),

    HAAKSBERGEN("HSC '21 Haaksbergen", LeagueEnum.NL_4),

    KLAKSVIK("KÍ Klaksvík", LeagueEnum.FO_1),
    HB("HB Tórshavn", LeagueEnum.FO_1),
    VIKINGUR_GOTA("Víkingur Gøta", LeagueEnum.FO_1),
    B36("B36 Tórshavn", LeagueEnum.FO_1),
    VESTUR("07 Vestur", LeagueEnum.FO_1),
    STREYMUR("EB/Streymur", LeagueEnum.FO_1),
    TOFTIR("B68 Toftir", LeagueEnum.FO_1),
    FUGLAFJORDUR("ÍF Fuglafjørður", LeagueEnum.FO_1),
    NSI("NSÍ Runavík", LeagueEnum.FO_1),
    SKALA("Skála IF", LeagueEnum.FO_1),

    ARGIR("AB Argir", LeagueEnum.FO_2),
    TVOROYRI("TB Tvøroyri", LeagueEnum.FO_2),
    VIKINGUR_GOTA_II("Víkingur Gøta II", LeagueEnum.FO_2),
    HB_II("HB Tórshavn II", LeagueEnum.FO_2),
    B36_II("B36 Tórshavn II", LeagueEnum.FO_2),
    KLAKSVIK_II("KÍ Klaksvík II", LeagueEnum.FO_2),
    NSI_II("NSÍ Runavík II", LeagueEnum.FO_2),
    B71("B71 Sandoy", LeagueEnum.FO_2),
    HOYVIK("FC Hoyvík", LeagueEnum.FO_2),
    SUDUROY("FC Suðuroy", LeagueEnum.FO_2),

    MIDVAGUR("MB Midvágur", LeagueEnum.FO_3),

    VIKINGUR_RVK("Víkingur Reykjavík", LeagueEnum.IS_1),
    VALUR("Valur Reykjavík", LeagueEnum.IS_1),
    BREIDABLIK("Breiðablik Kópavogur", LeagueEnum.IS_1),
    KR_RVK("KR Reykjavík", LeagueEnum.IS_1),
    STJARNAN("Stjarnan Garðabær", LeagueEnum.IS_1),
    AKUREYRI("KA Akureyri", LeagueEnum.IS_1),
    VESTRI("Vestri Ísafjörður", LeagueEnum.IS_1),
    HAFNARFJORDUR("FH Hafnarfjörður", LeagueEnum.IS_1),
    FRAM("Fram Reykjavík", LeagueEnum.IS_1),
    FYLKIR("Fylkir Reykjavík", LeagueEnum.IS_1),
    AKRANES("ÍA Akranes", LeagueEnum.IS_1),
    KOPAVOGUR("HK Kópavogs", LeagueEnum.IS_1),

    AFTURELDING("UMF Afturelding", LeagueEnum.IS_2),
    KEFLAVIK("Keflavík ÍF", LeagueEnum.IS_2),
    GRINDAVIK("UMF Grindavík", LeagueEnum.IS_2),
    IBV("ÍBV Vestmannaeyjar", LeagueEnum.IS_2),
    FJOLNIR("Fjölnir Reykjavík", LeagueEnum.IS_2),
    THOR("Þór Akureyri", LeagueEnum.IS_2),
    THROTTUR_RVK("Þróttur Reykjavík", LeagueEnum.IS_2),
    LEIKNIR("Leiknir Reykjavík", LeagueEnum.IS_2),
    GROTTA("ÍF Grótta", LeagueEnum.IS_2),
    NJARDVIK("UMF Njarðvík", LeagueEnum.IS_2),
    IR_RVK("ÍR Reykjavík", LeagueEnum.IS_2),
    DALVIK("Dalvík/Reynir", LeagueEnum.IS_2),

    SELFOSS("UMF Selfoss", LeagueEnum.IS_3),
    VIKINGUR_O("UMF Víkingur Ólafsvík", LeagueEnum.IS_3),
    THROTTUR_V("Þróttur Vogum", LeagueEnum.IS_3),
    AEGIR("KF Ægir", LeagueEnum.IS_3),
    KFG("KFG Garðabær", LeagueEnum.IS_3),
    KFA("KFA Austfjarða", LeagueEnum.IS_3),
    HOTTUR("Höttur/Huginn", LeagueEnum.IS_3),
    VOLSUNGUR("Völsungur ÍF", LeagueEnum.IS_3),
    HAUKAR("Haukar Hafnarfjörður", LeagueEnum.IS_3),
    FJALLABYGGD("KF Fjallabyggd", LeagueEnum.IS_3),
    SANDGERDI("Reynir Sandgerði", LeagueEnum.IS_3),
    KORMAKUR("Kormákur/Hvöt", LeagueEnum.IS_3),

    HJK("HJK Helsinki", LeagueEnum.FI_1),
    ILVES("Ilves Tampere", LeagueEnum.FI_1),
    KUOPIO("Kuopion Palloseura", LeagueEnum.FI_1),
    INTER_TURKU("FC Inter Turku", LeagueEnum.FI_1),
    OULU("AC Oulu", LeagueEnum.FI_1),
    SEINAJOKI("SJK Seinäjoki", LeagueEnum.FI_1),
    VAASA("Vaasan Palloseura", LeagueEnum.FI_1),
    LAHTI("FC Lahti", LeagueEnum.FI_1),
    HAKA("FC Haka", LeagueEnum.FI_1),
    MARIEHAMN("IFK Mariehamn", LeagueEnum.FI_1),
    GNISTAN("IF Gnistan", LeagueEnum.FI_1),
    EKENAS("Ekenäs IF", LeagueEnum.FI_1),

    KTP("FC KTP", LeagueEnum.FI_2),
    TURKU_P("Turun Palloseura", LeagueEnum.FI_2),
    SEINAJOKI_II("SJK Seinäjoki II", LeagueEnum.FI_2),
    JARO("FF Jaro", LeagueEnum.FI_2),
    JARVENPAA("Järvenpään Palloseura", LeagueEnum.FI_2),
    SALO("Salon Palloilijat", LeagueEnum.FI_2),
    KAPYLA("Käpylän Pallo", LeagueEnum.FI_2),
    MIKKELI("Mikkelin Palloilijat", LeagueEnum.FI_2),
    PALLOKERHO("Pallokerho-35", LeagueEnum.FI_2),
    JIPPO("JIPPO Joensuu", LeagueEnum.FI_2),

    JYVASKYLA("JJK Jyväskylä", LeagueEnum.FI_3),
    KOKKOLA("Kokkolan Pallo-Veikot", LeagueEnum.FI_3),
    HJK_KLUBI("HJK Klubi 04 Helsinki", LeagueEnum.FI_3),
    OULU_L("Oulun Luistinseura", LeagueEnum.FI_3),
    VAAJAKOSKI("FC Vaajakoski", LeagueEnum.FI_3),
    KUOPIO_II("Kuopion Palloseura II", LeagueEnum.FI_3),
    ESPOO("Espoon Palloseura", LeagueEnum.FI_3),
    FC_JAZZ("FC Jazz", LeagueEnum.FI_3),
    ATLANTIS("Atlantis FC", LeagueEnum.FI_3),
    ROVANIEMI("Rovaniemen Palloseura", LeagueEnum.FI_3),
    IFK_VAASA("Vaasa IFK", LeagueEnum.FI_3),
    KESKI_UUSIMAA("Pallokerho Keski-Uusimaa", LeagueEnum.FI_3),

    LEVADIA("FCI Levadia", LeagueEnum.EE_1),
    PAIDE("Paide Linnameeskond", LeagueEnum.EE_1),
    FLORA_TALLINN("FC Flora Tallinn", LeagueEnum.EE_1),
    PARNU("Pärnu JK Vapras", LeagueEnum.EE_1),
    KALJU("Kalju FC", LeagueEnum.EE_1),
    KALEV("Kalev Tallinn", LeagueEnum.EE_1),
    TAMMEKA("Jalgpallikool Tammeka", LeagueEnum.EE_1),
    KURESSAARE("FC Kuressaare", LeagueEnum.EE_1),
    NARVA("JK Trans Narva", LeagueEnum.EE_1),
    NOMME("FC Nõmme United", LeagueEnum.EE_1),

    COPENHAGEN("FC København", LeagueEnum.DK_1),
    NORDSJAELLAND("FC Nordsjælland", LeagueEnum.DK_1),
    MIDTJYLLAND("FC Midtjylland", LeagueEnum.DK_1),
    BRONDBY("Brøndby IF", LeagueEnum.DK_1),
    AARHUS("Aarhus GF", LeagueEnum.DK_1),
    SILKEBORG("Silkeborg IF", LeagueEnum.DK_1),
    VIBORG("Viborg FF", LeagueEnum.DK_1),
    ODENSE("Odense BK", LeagueEnum.DK_1),
    RANDERS("Randers FC", LeagueEnum.DK_1),
    VEJLE("Vejle Boldklub", LeagueEnum.DK_1),
    LYNGBY("Lyngby BK", LeagueEnum.DK_1),
    HVIDOVRE("Hvidovre IF", LeagueEnum.DK_1),

    AALBORG("Aalborg BK", LeagueEnum.DK_2),
    SONDERJYSKE("Sønderjyske", LeagueEnum.DK_2),
    HORSENS("AC Horsens", LeagueEnum.DK_2),
    VENDSYSSEL("Vendsyssel FF", LeagueEnum.DK_2),
    HELSINGOR("FC Helsingør", LeagueEnum.DK_2),
    FREDERICIA("FC Fredericia", LeagueEnum.DK_2),
    HOBRO("Hobro IK", LeagueEnum.DK_2),
    NAESTVED("Næstved Boldklub", LeagueEnum.DK_2),
    HILLEROD("Hillerød Fodbold", LeagueEnum.DK_2),
    KOGE("HB Køge", LeagueEnum.DK_2),
    BK_1893("Boldklubben af 1893", LeagueEnum.DK_2),
    KOLDING("Kolding IF", LeagueEnum.DK_2),

    AMAGER("BK Fremad Amager", LeagueEnum.DK_3),
    AKADEMISK("Akademisk BK", LeagueEnum.DK_3),
    MIDDELFART("Middelfart Boldklub", LeagueEnum.DK_3),
    NYKOBING("Nykøbing FC", LeagueEnum.DK_3),
    HELLERUP("Hellerup IK", LeagueEnum.DK_3),
    AARHUS_F("Aarhus Fremad", LeagueEnum.DK_3),
    ROSKILDE("FC Roskilde", LeagueEnum.DK_3),
    THISTED("Thisted FC", LeagueEnum.DK_3),
    ESBJERG("Esbjerg fB", LeagueEnum.DK_3),
    BRABRAND("Brabrand IF", LeagueEnum.DK_3),
    SKIVE("Skive IK", LeagueEnum.DK_3),
    FA_2000("FA 2000", LeagueEnum.DK_3),

    BODO("FK Bodø/Glimt", LeagueEnum.NO_1),
    ROSENBORG("Rosenborg BK", LeagueEnum.NO_1),
    MOLDE("Molde FK", LeagueEnum.NO_1),
    VIKING("Viking FK", LeagueEnum.NO_1),
    BRANN("SK Brann", LeagueEnum.NO_1),
    TROMSO("Tromsø IL", LeagueEnum.NO_1),
    LILLESTROM("Lillestrøm SK", LeagueEnum.NO_1),
    ODDS("Odds BK", LeagueEnum.NO_1),
    HAUGESUND("FK Haugesund", LeagueEnum.NO_1),
    SARPSBORG("Sarpsborg 08 FF", LeagueEnum.NO_1),
    STROMSGODSET("Strømsgodset IF", LeagueEnum.NO_1),
    SANDEFJORD("Sandefjord Fotball", LeagueEnum.NO_1),
    FREDRIKSTAD("Fredrikstad FK", LeagueEnum.NO_1),
    KFUM("KFUM Kameratene Oslo", LeagueEnum.NO_1),
    HAMKAM("Hamarkameratene", LeagueEnum.NO_1),
    KRISTIANSUND("Kristiansund BK", LeagueEnum.NO_1),

    VALERENGA("Vålerenga Fotball Elite", LeagueEnum.NO_2),
    AALESUND("Aalesunds FK", LeagueEnum.NO_2),
    STABAEK("Stabæk Fotball", LeagueEnum.NO_2),
    RANHEIM("Ranheim IL", LeagueEnum.NO_2),
    KONGSVINGER("Kongsvinger IL", LeagueEnum.NO_2),
    START("IK Start", LeagueEnum.NO_2),
    SOGNDAL("Sogndal IL Fotball", LeagueEnum.NO_2),
    MJONDALEN("Mjøndalen IF", LeagueEnum.NO_2),
    MOSS("Moss FK", LeagueEnum.NO_2),
    BRYNE("Bryne FK", LeagueEnum.NO_2),
    ASANE("Åsane Fotball", LeagueEnum.NO_2),
    LEVANGER("Levanger FK", LeagueEnum.NO_2),
    SANDNES("Sandnes Ulf", LeagueEnum.NO_2),
    EGERSUND("Egersunds IK", LeagueEnum.NO_2),
    LYN_FK("Lyn 1896 FK", LeagueEnum.NO_2),
    RAUFOSS("Raufoss IL", LeagueEnum.NO_2),

    JERV("FK Jerv", LeagueEnum.NO_3),
    BRANN_II("SK Brann II", LeagueEnum.NO_3),
    HODD("IL Hødd", LeagueEnum.NO_3),
    ARENDAL("Arendal Fotball", LeagueEnum.NO_3),
    BRATTVAG("Brattvåg IL", LeagueEnum.NO_3),
    SK_VARD("SK Vard Haugesund", LeagueEnum.NO_3),
    VIKING_II("Viking FK II", LeagueEnum.NO_3),
    TONSBERG("FK Eik Tønsberg 871", LeagueEnum.NO_3),
    FLEKKEROY("Flekkerøy IF", LeagueEnum.NO_3),
    KVIK("Kvik Halden", LeagueEnum.NO_3),
    LYSEKLOSTER("Lysekloster IL", LeagueEnum.NO_3),
    NOTODDEN("Notodden FK", LeagueEnum.NO_3),
    SOTRA("Sotra SK", LeagueEnum.NO_3),
    HORTEN("FK Ørn Horten", LeagueEnum.NO_3),
    VALERENGA_II("Vålerenga Fotball II", LeagueEnum.NO_3),
    SKEID("Skeid Oslo", LeagueEnum.NO_3),
    TROMSDALEN("Tromsdalen UIL", LeagueEnum.NO_3),
    GRORUD("Grorud IL", LeagueEnum.NO_3),
    STJORDAL("Stjørdals-Blink Fotball", LeagueEnum.NO_3),
    ALTA("Alta IF", LeagueEnum.NO_3),
    EIDSVOLD("Eidsvold Turn Fotball", LeagueEnum.NO_3),
    FOLLO("Follo FK", LeagueEnum.NO_3),
    GJOVIK("FK Gjøvik-Lyn", LeagueEnum.NO_3),
    JUNKEREN("Junkeren IK", LeagueEnum.NO_3),
    KJELSAS("Kjelsås IF", LeagueEnum.NO_3),
    STRINDHEIM("Strindheim TF", LeagueEnum.NO_3),
    STROMMEN("Strømmen IF", LeagueEnum.NO_3),
    ULLENSAKER("Ullensaker/Kisa IL", LeagueEnum.NO_3),

    //TODO add clubs from NO_4 (84 clubs)
    TRAEFF("SK Træff", LeagueEnum.NO_4),

    MALMO("Malmö FF", LeagueEnum.SE_1),
    HACKEN("BK Häcken", LeagueEnum.SE_1),
    HAMMARBY("Hammarby IF", LeagueEnum.SE_1),
    ELFSBORG("IF Elfsborg", LeagueEnum.SE_1),
    DJURGARDEN("Djurgårdens IF", LeagueEnum.SE_1),
    AIK("AIK Solna", LeagueEnum.SE_1),
    GOTEBORG("IFK Göteborg", LeagueEnum.SE_1),
    NORRKOPING("IFK Norrköping", LeagueEnum.SE_1),
    SIRIUS("IK Sirius", LeagueEnum.SE_1),
    KALMAR("Kalmar FF", LeagueEnum.SE_1),
    BROMMA("IF Brommapojkarna", LeagueEnum.SE_1),
    HALMSTAD("Halmstads BK", LeagueEnum.SE_1),
    MJALLBY("Mjällby AIF", LeagueEnum.SE_1),
    VARNAMO("IFK Värnamo", LeagueEnum.SE_1),
    GAIS("GAIS", LeagueEnum.SE_1),
    VASTERAS("Västerås SK", LeagueEnum.SE_1),

    OSTERS("Östers IF", LeagueEnum.SE_2),
    VARBERGS("Varbergs BoIS", LeagueEnum.SE_2),
    TRELLEBORGS("Trelleborgs FF", LeagueEnum.SE_2),
    HELSINGBORG("Helsingborgs IF", LeagueEnum.SE_2),
    BRAGE("IK Brage", LeagueEnum.SE_2),
    DEGERFORS("Degerfors IF", LeagueEnum.SE_2),
    LANDSKRONA("Landskrona BoIS", LeagueEnum.SE_2),
    OSTERSUND("Östersunds FK", LeagueEnum.SE_2),
    SUNDSVALL("GIF Sundsvall", LeagueEnum.SE_2),
    UTSIKTEN("Utsiktens BK", LeagueEnum.SE_2),
    OREBRO("Örebro SK", LeagueEnum.SE_2),
    ORGRYTE("Örgryte IS", LeagueEnum.SE_2),
    GEFLE("Gefle IF", LeagueEnum.SE_2),
    SKOVDE("Skövde AIK", LeagueEnum.SE_2),
    SANDVIKEN("Sandvikens IF", LeagueEnum.SE_2),
    ODDEVOLD("IK Oddevold", LeagueEnum.SE_2),

    ESKILSTUNA("AFC Eskilstuna", LeagueEnum.SE_3_1),
    DALKURD("Dalkurd FF", LeagueEnum.SE_3_1),
    KARLSTAD("IF Karlstad", LeagueEnum.SE_3_1),
    LJUNGSKILE("Ljungskile SK", LeagueEnum.SE_3_2),
    BK_OLYMPIC("BK Olympic", LeagueEnum.SE_3_2),

    FUZINAR("NK Fuzinar", LeagueEnum.SI_1),

    NOVI_PAZAR("FK Novi Pazar", LeagueEnum.RS_1),
    VOZDOVAC("FK Vozdovac", LeagueEnum.RS_1),
    CUKARICKI("FK Cukaricki", LeagueEnum.RS_1),

    MACVA("FK Macva Sabac", LeagueEnum.RS_2),

    ALL_BOYS("CA All Boys", LeagueEnum.AR_2),

    PETROLERO("Club Independiente Petrolero", LeagueEnum.BO_1),

    INDY_ELEVEN("Indy Eleven", LeagueEnum.US_2);

    private final String name;
    private LeagueEnum league;

    ClubEnum(String name, LeagueEnum league) {
        this.name = name;
        this.league = league;
    }

    public List<ClubEnum> getByLeague(LeagueEnum league) {
        if (league == null) return null;

        List<ClubEnum> result = new ArrayList<>();
        for (ClubEnum c : ClubEnum.values()) {
            if (c.getLeague().equals(league)) {
                result.add(c);
            }
        }
        return result;
    }

    public ClubEnum getByEnumName(String enumName) {
        if (enumName == null || enumName.trim().isEmpty()) {
            return null;
        }

        for (ClubEnum c : ClubEnum.values()) {
            if (c.toString().equals(enumName)) {
                return c;
            }
        }

        return null;
    }

    public String getName() {
        return name;
    }

    public LeagueEnum getLeague() {
        return league;
    }

    public void setLeague(LeagueEnum league) {
        this.league = league;
    }
}
