package enums;

import java.util.ArrayList;
import java.util.List;

public enum Club {
    WITHOUT_CLUB("Without club", League.WITHOUT_CLUB),

    MAN_CITY("Manchester City", League.ENG_1),
    ARSENAL("FC Arsenal", League.ENG_1),
    CHELSEA("FC Chelsea", League.ENG_1),
    LIVERPOOL("FC Liverpool", League.ENG_1),
    MAN_UTD("Manchester United", League.ENG_1),
    SPURS("Tottenham Hotspur", League.ENG_1),
    NEWCASTLE("Newcastle United", League.ENG_1),
    ASTON_VILLA("Aston Villa", League.ENG_1),
    BRIGHTON("Brighton & Hove Albion", League.ENG_1),
    WESTHAM("West Ham United", League.ENG_1),
    BRENTFORD("FC Brentford", League.ENG_1),
    NHAM_FOREST("Nottingham Forest", League.ENG_1),
    CRYSTAL_PALACE("Crystal Palace", League.ENG_1),
    EVERTON("FC Everton", League.ENG_1),
    BOURNEMOUTH("AFC Bournemouth", League.ENG_1),
    WOLVES("Wolverhampton Wanderers", League.ENG_1),
    FULHAM("FC Fulham", League.ENG_1),
    BURNLEY("FC Burnley", League.ENG_1),
    SHEFFIELD_UTD("Sheffield United", League.ENG_1),
    LUTON("Luton Town", League.ENG_1),

    LEICESTER("Leicester City", League.ENG_2),
    SOUTHAMPTON("FC Southampton", League.ENG_2),
    LEEDS("Leeds United", League.ENG_2),
    SUNDERLAND("AFC Sunderland", League.ENG_2),
    HULL_CITY("Hull City", League.ENG_2),
    MIDDLESBROUGH("FC Middlesbrough", League.ENG_2),
    NORWICH("Norwich City", League.ENG_2),
    BLACKBURN("Blackburn Rovers", League.ENG_2),
    SWANSEA("Swansea City", League.ENG_2),
    WATFORD("FC Watford", League.ENG_2),
    STOKE("Stoke City", League.ENG_2),
    WEST_BROM("West Bromwich Albion", League.ENG_2),
    COVENTRY("Coventry City", League.ENG_2),
    BIRMINGHAM("Birmingham City", League.ENG_2),
    IPSWICH("Ipswich Town", League.ENG_2),
    CARDIFF("Cardiff City", League.ENG_2),
    PRESTON_NE("Preston North End", League.ENG_2),
    MILLWALL("FC Millwall", League.ENG_2),
    BRISTOL("Bristol City", League.ENG_2),
    HUDDERSFIELD("Huddersfield Town", League.ENG_2),
    QUEENS_PR("Queens Park Rangers", League.ENG_2),
    PLYMOUTH("Plymouth Argyle", League.ENG_2),
    ROTHERHAM("Rotherham United", League.ENG_2),
    SHEFFIELD_W("Sheffield Wednesday", League.ENG_2),

    PBOROUGH("Peterborough United", League.ENG_3),
    DERBY_COUNTY("Derby County", League.ENG_3),
    BARNSLEY("FC Barnsley", League.ENG_3),
    READING("FC Reading", League.ENG_3),
    BLACKPOOL("FC Blackpool", League.ENG_3),
    CHARLTON("Charlton Athletic", League.ENG_3),
    PORTSMOUTH("FC Portsmouth", League.ENG_3),
    BOLTON("Bolton Wanderers", League.ENG_3),
    WIGAN("Wigan Athletic", League.ENG_3),
    BRISTOL_ROVERS("Bristol Rovers", League.ENG_3),
    OXFORD("Oxford United", League.ENG_3),
    EXETER("Exeter City", League.ENG_3),
    LINCOLN("Lincoln City", League.ENG_3),
    FLEETWOOD("Fleetwood Town", League.ENG_3),
    WYCOMBE("Wycombe Wanderers", League.ENG_3),
    PORT_VALE("FC Port Vale", League.ENG_3),
    STEVENAGE("FC Stevenage", League.ENG_3),
    CARLISLE("Carlisle United", League.ENG_3),
    SHREWSBURY("Shrewsbury Town", League.ENG_3),
    NORTHAMPTON("Northampton Town", League.ENG_3),
    LEYTON("Leyton Orient", League.ENG_3),
    CAMBRIDGE("Cambrige United", League.ENG_3),
    BURTON("Burton Albion", League.ENG_3),
    CHELTENHAM("Cheltenham Town", League.ENG_3),

    WREXHAM("AFC Wrexham", League.ENG_4),
    STOCKPORT("Stockport County", League.ENG_4),
    FOREST_GREEN("Forest Green Rovers", League.ENG_4),
    COLCHESTER("Colchester United", League.ENG_4),
    MK_DONS("Milton Keynes Dons", League.ENG_4),
    CREWE("Crewe Alexandra", League.ENG_4),
    BRADFORD("Bradford City", League.ENG_4),
    GRIMSBY("Grimsby Town", League.ENG_4),
    DONCASTER("Doncaster Rovers", League.ENG_4),
    MANSFIELD("Mansfield", League.ENG_4),
    SALFORD("Salford City", League.ENG_4),
    GILLINGHAM("FC Gillingham", League.ENG_4),
    WALSALL("FC Walsall", League.ENG_4),
    BARROW("AFC Barrow", League.ENG_4),
    WIMBLEDON("AFC Wimbledon", League.ENG_4),
    MORECAMBE("FC Morecambe", League.ENG_4),
    NOTTS_COUNTY("Notts County", League.ENG_4),
    STANLEY("Accrington Stanley", League.ENG_4),
    TRANMERE("Tranmere Rovers", League.ENG_4),
    NEWPORT("Newport County", League.ENG_4),
    SWINDON("Swindon Town", League.ENG_4),
    HARROGATE("Harrogate Town", League.ENG_4),
    SUTTON("Sutton United", League.ENG_4),
    CRAWLEY("Crawley Town", League.ENG_4),

    BAYERN("Bayern München", League.DE_1),
    LEVERKUSEN("Bayer 04 Leverkusen", League.DE_1),
    LEIPZIG("RB Leipzig", League.DE_1),
    BVB("Borussia Dortmund", League.DE_1),
    WOLFSBURG("VfL Wolfsburg", League.DE_1),
    FRANKFURT("Eintracht Frankfurt", League.DE_1),
    STUTTGART("VfB Stuttgart", League.DE_1),
    BORUSSIA_M("Borussia Mönchengladbach", League.DE_1),
    FREIBURG("SC Freiburg", League.DE_1),
    UNION("1.FC Union Berlin", League.DE_1),
    TSG("TSG 1899 Hoffenheim", League.DE_1),
    AUGSBURG("FC Augsburg", League.DE_1),
    MAINZ("FSV Mainz 05", League.DE_1),
    KOLN("1.FC Köln", League.DE_1),
    BREMEN("SV Werder Bremen", League.DE_1),
    BOCHUM("VfL Bochum", League.DE_1),
    HEIDENHEIM("1.FC Heidenheim 1846", League.DE_1),
    DARMSTADT("SV Darmstadt 98", League.DE_1),

    HSV("Hamburger SV", League.DE_2),
    HERTHA("Hertha BSC", League.DE_2),
    DUSSELDORF("Fortuna Düsseldorf", League.DE_2),
    SCHALKE("Schalke 04", League.DE_2),
    NURNBERG("1.FC Nürnberg", League.DE_2),
    HANNOVER("Hannover 96", League.DE_2),
    STPAULI("FC St. Pauli", League.DE_2),
    KIEL("Holstein Kiel", League.DE_2),
    FURTH("SpVgg Greuther Fürth", League.DE_2),
    KAISERSLAUTERN("1.FC Kaiserslautern", League.DE_2),
    PADERBORN("SC Paderborn 07", League.DE_2),
    ELVERSBERG("SV 07 Elversberg", League.DE_2),
    MAGDEBURG("1.FC Magdeburg", League.DE_2),
    KSC("Karlsruher SC", League.DE_2),
    WIESBADEN("SV Wehen Wiesbaden", League.DE_2),
    ROSTOCK("FC Hansa Rostock", League.DE_2),
    OSNABRUCK("VfL Osnabrück", League.DE_2),
    BRAUNSCHWEIG("Eintracht Braunschweig", League.DE_2),

    BVB_II("Borussia Dortmund II", League.DE_3),
    DYNAMO_DRESDEN("SG Dynamo Dresden", League.DE_3),
    FREIBURG_II("SC Freiburg II", League.DE_3),
    SANDHAUSEN("SV Sandhausen", League.DE_3),
    INGOLSTADT("FC Ingolstadt 04", League.DE_3),
    DUISBURG("MSV Duisburg", League.DE_3),
    REGENSBURG("SSV Jahn Regensburg", League.DE_3),
    BIELEFELD("Arminia Bielefeld", League.DE_3),
    SAARBRUCKEN("1.FC Saarbrücken", League.DE_3),
    HALLESCHER("Hallescher FC", League.DE_3),
    MUNICH_1860("TSV 1860 München", League.DE_3),
    MANNHEIM("SV Waldhof Mannheim", League.DE_3),
    VIKTORIA_KOLN("FC Viktoria Köln", League.DE_3),
    RW_ESSEN("Rot-Weiss Essen", League.DE_3),
    PREUSSEN("Preußen Münster", League.DE_3),
    VERL("SC Verl", League.DE_3),
    ERZGEBIRGE("FC Erzgebirge Aue", League.DE_3),
    ULM("SSV Ulm 1846", League.DE_3),
    UNTERHACHING("SpVgg Unterhaching", League.DE_3),
    LUBECK("VfB Lübeck", League.DE_3),

    VIKTORIA_BERLIN("FC Viktoria 1889 Berlin", League.DE_4),

    REAL_MADRID("Real Madrid", League.ES_1),
    BARCA("FC Barcelona", League.ES_1),
    SOCIEDAD("Real Sociedad", League.ES_1),
    ATLETICO("Atlético Madrid", League.ES_1),
    ATHLETIC("Athletic Bilbao", League.ES_1),
    GIRONA("FC Girona", League.ES_1),
    VILLARREAL("FC Villarreal", League.ES_1),
    BETIS("Real Betis", League.ES_1),
    VALENCIA("FC Valencia", League.ES_1),
    SEVILLA("FC Sevilla", League.ES_1),
    GETAFE("FC Getafe", League.ES_1),
    OSASUNA("CD Osasuna", League.ES_1),
    CELTA("Celta Vigo", League.ES_1),
    ALMERIA("UD Almería", League.ES_1),
    MALLORCA("RCD Mallorca", League.ES_1),
    GRANADA("FC Granada", League.ES_1),
    RAYO("Rayo Vallecano", League.ES_1),
    ALAVES("Deportivo Alavés", League.ES_1),
    LAS_PALMAS("UD Las Palmas", League.ES_1),
    CADIZ("FC Cádiz", League.ES_1),

    ESPANYOL("Espanyol", League.ES_2),
    VALLADOLID("Real Valladolid", League.ES_2),
    SARAGOSSA("Real Saragossa", League.ES_2),
    ELCHE("FC Elche", League.ES_2),
    OVIEDO("Real Oviedo", League.ES_2),
    GIJON("Sporting Gijón", League.ES_2),
    EIBAR("SD Eibar", League.ES_2),
    LEVANTE("UD Levante", League.ES_2),
    LEGANES("CD Leganés", League.ES_2),
    VILLARREAL_B("FC Villarreal B", League.ES_2),
    ANDORRA("FC Andorra", League.ES_2),
    TENERIFFA("CD Teneriffa", League.ES_2),
    RACING("Racing Santander", League.ES_2),
    HUESCA("SD Huesca", League.ES_2),
    ALBACETE("Albacete Balompié", League.ES_2),
    MIRANDES("CD Mirandés", League.ES_2),
    BURGOS("Burgos CF", League.ES_2),
    CARTAGENA("FC Cartagena", League.ES_2),
    FERROL("Racing Ferrol", League.ES_2),
    ELDENSE("CD Eldense", League.ES_2),
    ALCORCON("AD Alcorcón", League.ES_2),
    AMOREBIETA("SD Amorebieta", League.ES_2),

    ANTONIANO("Club Atlético Antoniano", League.ES_4),

    BRENO("USD Breno", League.IT_4),

    FORFAR("Forfar Athletic FC", League.SCO_2),

    KEITH("Keith FC", League.SCO_5),

    DUNDALK("Dundalk FC", League.IE_1),

    VIANENSE("SC Vianense", League.PT_3),

    DEN_BOSCH("FC Den Bosch", League.NL_2),

    HAAKSBERGEN("HSC '21 Haaksbergen", League.NL_4),

    KLAKSVIK("KÍ Klaksvík", League.FO_1),
    HB("HB Tórshavn", League.FO_1),
    VIKINGUR_GOTA("Víkingur Gøta", League.FO_1),
    B36("B36 Tórshavn", League.FO_1),
    VESTUR("07 Vestur", League.FO_1),
    STREYMUR("EB/Streymur", League.FO_1),
    TOFTIR("B68 Toftir", League.FO_1),
    FUGLAFJORDUR("ÍF Fuglafjørður", League.FO_1),
    NSI("NSÍ Runavík", League.FO_1),
    SKALA("Skála IF", League.FO_1),

    ARGIR("AB Argir", League.FO_2),
    TVOROYRI("TB Tvøroyri", League.FO_2),
    VIKINGUR_GOTA_II("Víkingur Gøta II", League.FO_2),
    HB_II("HB Tórshavn II", League.FO_2),
    B36_II("B36 Tórshavn II", League.FO_2),
    KLAKSVIK_II("KÍ Klaksvík II", League.FO_2),
    NSI_II("NSÍ Runavík II", League.FO_2),
    B71("B71 Sandoy", League.FO_2),
    HOYVIK("FC Hoyvík", League.FO_2),
    SUDUROY("FC Suðuroy", League.FO_2),

    MIDVAGUR("MB Midvágur", League.FO_3),

    VIKINGUR_RVK("Víkingur Reykjavík", League.IS_1),
    VALUR("Valur Reykjavík", League.IS_1),
    BREIDABLIK("Breiðablik Kópavogur", League.IS_1),
    KR_RVK("KR Reykjavík", League.IS_1),
    STJARNAN("Stjarnan Garðabær", League.IS_1),
    AKUREYRI("KA Akureyri", League.IS_1),
    VESTRI("Vestri Ísafjörður", League.IS_1),
    HAFNARFJORDUR("FH Hafnarfjörður", League.IS_1),
    FRAM("Fram Reykjavík", League.IS_1),
    FYLKIR("Fylkir Reykjavík", League.IS_1),
    AKRANES("ÍA Akranes", League.IS_1),
    KOPAVOGUR("HK Kópavogs", League.IS_1),

    AFTURELDING("UMF Afturelding", League.IS_2),
    KEFLAVIK("Keflavík ÍF", League.IS_2),
    GRINDAVIK("UMF Grindavík", League.IS_2),
    IBV("ÍBV Vestmannaeyjar", League.IS_2),
    FJOLNIR("Fjölnir Reykjavík", League.IS_2),
    THOR("Þór Akureyri", League.IS_2),
    THROTTUR_RVK("Þróttur Reykjavík", League.IS_2),
    LEIKNIR("Leiknir Reykjavík", League.IS_2),
    GROTTA("ÍF Grótta", League.IS_2),
    NJARDVIK("UMF Njarðvík", League.IS_2),
    IR_RVK("ÍR Reykjavík", League.IS_2),
    DALVIK("Dalvík/Reynir", League.IS_2),

    SELFOSS("UMF Selfoss", League.IS_3),
    VIKINGUR_O("UMF Víkingur Ólafsvík", League.IS_3),
    THROTTUR_V("Þróttur Vogum", League.IS_3),
    AEGIR("KF Ægir", League.IS_3),
    KFG("KFG Garðabær", League.IS_3),
    KFA("KFA Austfjarða", League.IS_3),
    HOTTUR("Höttur/Huginn", League.IS_3),
    VOLSUNGUR("Völsungur ÍF", League.IS_3),
    HAUKAR("Haukar Hafnarfjörður", League.IS_3),
    FJALLABYGGD("KF Fjallabyggd", League.IS_3),
    SANDGERDI("Reynir Sandgerði", League.IS_3),
    KORMAKUR("Kormákur/Hvöt", League.IS_3),

    HJK("HJK Helsinki", League.FI_1),
    ILVES("Ilves Tampere", League.FI_1),
    KUOPIO("Kuopion Palloseura", League.FI_1),
    INTER_TURKU("FC Inter Turku", League.FI_1),
    OULU("AC Oulu", League.FI_1),
    SEINAJOKI("SJK Seinäjoki", League.FI_1),
    VAASA("Vaasan Palloseura", League.FI_1),
    LAHTI("FC Lahti", League.FI_1),
    HAKA("FC Haka", League.FI_1),
    MARIEHAMN("IFK Mariehamn", League.FI_1),
    GNISTAN("IF Gnistan", League.FI_1),
    EKENAS("Ekenäs IF", League.FI_1),

    KTP("FC KTP", League.FI_2),
    TURKU_P("Turun Palloseura", League.FI_2),
    SEINAJOKI_II("SJK Seinäjoki II", League.FI_2),
    JARO("FF Jaro", League.FI_2),
    JARVENPAA("Järvenpään Palloseura", League.FI_2),
    SALO("Salon Palloilijat", League.FI_2),
    KAPYLA("Käpylän Pallo", League.FI_2),
    MIKKELI("Mikkelin Palloilijat", League.FI_2),
    PALLOKERHO("Pallokerho-35", League.FI_2),
    JIPPO("JIPPO Joensuu", League.FI_2),

    JYVASKYLA("JJK Jyväskylä", League.FI_3),
    KOKKOLA("Kokkolan Pallo-Veikot", League.FI_3),
    HJK_KLUBI("HJK Klubi 04 Helsinki", League.FI_3),
    OULU_L("Oulun Luistinseura", League.FI_3),
    VAAJAKOSKI("FC Vaajakoski", League.FI_3),
    KUOPIO_II("Kuopion Palloseura II", League.FI_3),
    ESPOO("Espoon Palloseura", League.FI_3),
    FC_JAZZ("FC Jazz", League.FI_3),
    ATLANTIS("Atlantis FC", League.FI_3),
    ROVANIEMI("Rovaniemen Palloseura", League.FI_3),
    IFK_VAASA("Vaasa IFK", League.FI_3),
    KESKI_UUSIMAA("Pallokerho Keski-Uusimaa", League.FI_3),

    LEVADIA("FCI Levadia", League.EE_1),
    PAIDE("Paide Linnameeskond", League.EE_1),
    FLORA_TALLINN("FC Flora Tallinn", League.EE_1),
    PARNU("Pärnu JK Vapras", League.EE_1),
    KALJU("Kalju FC", League.EE_1),
    KALEV("Kalev Tallinn", League.EE_1),
    TAMMEKA("Jalgpallikool Tammeka", League.EE_1),
    KURESSAARE("FC Kuressaare", League.EE_1),
    NARVA("JK Trans Narva", League.EE_1),
    NOMME("FC Nõmme United", League.EE_1),

    COPENHAGEN("FC København", League.DK_1),
    NORDSJAELLAND("FC Nordsjælland", League.DK_1),
    MIDTJYLLAND("FC Midtjylland", League.DK_1),
    BRONDBY("Brøndby IF", League.DK_1),
    AARHUS("Aarhus GF", League.DK_1),
    SILKEBORG("Silkeborg IF", League.DK_1),
    VIBORG("Viborg FF", League.DK_1),
    ODENSE("Odense BK", League.DK_1),
    RANDERS("Randers FC", League.DK_1),
    VEJLE("Vejle Boldklub", League.DK_1),
    LYNGBY("Lyngby BK", League.DK_1),
    HVIDOVRE("Hvidovre IF", League.DK_1),

    AALBORG("Aalborg BK", League.DK_2),
    SONDERJYSKE("Sønderjyske", League.DK_2),
    HORSENS("AC Horsens", League.DK_2),
    VENDSYSSEL("Vendsyssel FF", League.DK_2),
    HELSINGOR("FC Helsingør", League.DK_2),
    FREDERICIA("FC Fredericia", League.DK_2),
    HOBRO("Hobro IK", League.DK_2),
    NAESTVED("Næstved Boldklub", League.DK_2),
    HILLEROD("Hillerød Fodbold", League.DK_2),
    KOGE("HB Køge", League.DK_2),
    BK_1893("Boldklubben af 1893", League.DK_2),
    KOLDING("Kolding IF", League.DK_2),

    AMAGER("BK Fremad Amager", League.DK_3),
    AKADEMISK("Akademisk BK", League.DK_3),
    MIDDELFART("Middelfart Boldklub", League.DK_3),
    NYKOBING("Nykøbing FC", League.DK_3),
    HELLERUP("Hellerup IK", League.DK_3),
    AARHUS_F("Aarhus Fremad", League.DK_3),
    ROSKILDE("FC Roskilde", League.DK_3),
    THISTED("Thisted FC", League.DK_3),
    ESBJERG("Esbjerg fB", League.DK_3),
    BRABRAND("Brabrand IF", League.DK_3),
    SKIVE("Skive IK", League.DK_3),
    FA_2000("FA 2000", League.DK_3),

    BODO("FK Bodø/Glimt", League.NO_1),
    ROSENBORG("Rosenborg BK", League.NO_1),
    MOLDE("Molde FK", League.NO_1),
    VIKING("Viking FK", League.NO_1),
    BRANN("SK Brann", League.NO_1),
    TROMSO("Tromsø IL", League.NO_1),
    LILLESTROM("Lillestrøm SK", League.NO_1),
    ODDS("Odds BK", League.NO_1),
    HAUGESUND("FK Haugesund", League.NO_1),
    SARPSBORG("Sarpsborg 08 FF", League.NO_1),
    STROMSGODSET("Strømsgodset IF", League.NO_1),
    SANDEFJORD("Sandefjord Fotball", League.NO_1),
    FREDRIKSTAD("Fredrikstad FK", League.NO_1),
    KFUM("KFUM Kameratene Oslo", League.NO_1),
    HAMKAM("Hamarkameratene", League.NO_1),
    KRISTIANSUND("Kristiansund BK", League.NO_1),

    VALERENGA("Vålerenga Fotball Elite", League.NO_2),
    AALESUND("Aalesunds FK", League.NO_2),
    STABAEK("Stabæk Fotball", League.NO_2),
    RANHEIM("Ranheim IL", League.NO_2),
    KONGSVINGER("Kongsvinger IL", League.NO_2),
    START("IK Start", League.NO_2),
    SOGNDAL("Sogndal IL Fotball", League.NO_2),
    MJONDALEN("Mjøndalen IF", League.NO_2),
    MOSS("Moss FK", League.NO_2),
    BRYNE("Bryne FK", League.NO_2),
    ASANE("Åsane Fotball", League.NO_2),
    LEVANGER("Levanger FK", League.NO_2),
    SANDNES("Sandnes Ulf", League.NO_2),
    EGERSUND("Egersunds IK", League.NO_2),
    LYN_FK("Lyn 1896 FK", League.NO_2),
    RAUFOSS("Raufoss IL", League.NO_2),

    JERV("FK Jerv", League.NO_3),
    BRANN_II("SK Brann II", League.NO_3),
    HODD("IL Hødd", League.NO_3),
    ARENDAL("Arendal Fotball", League.NO_3),
    BRATTVAG("Brattvåg IL", League.NO_3),
    SK_VARD("SK Vard Haugesund", League.NO_3),
    VIKING_II("Viking FK II", League.NO_3),
    TONSBERG("FK Eik Tønsberg 871", League.NO_3),
    FLEKKEROY("Flekkerøy IF", League.NO_3),
    KVIK("Kvik Halden", League.NO_3),
    LYSEKLOSTER("Lysekloster IL", League.NO_3),
    NOTODDEN("Notodden FK", League.NO_3),
    SOTRA("Sotra SK", League.NO_3),
    HORTEN("FK Ørn Horten", League.NO_3),
    VALERENGA_II("Vålerenga Fotball II", League.NO_3),
    SKEID("Skeid Oslo", League.NO_3),
    TROMSDALEN("Tromsdalen UIL", League.NO_3),
    GRORUD("Grorud IL", League.NO_3),
    STJORDAL("Stjørdals-Blink Fotball", League.NO_3),
    ALTA("Alta IF", League.NO_3),
    EIDSVOLD("Eidsvold Turn Fotball", League.NO_3),
    FOLLO("Follo FK", League.NO_3),
    GJOVIK("FK Gjøvik-Lyn", League.NO_3),
    JUNKEREN("Junkeren IK", League.NO_3),
    KJELSAS("Kjelsås IF", League.NO_3),
    STRINDHEIM("Strindheim TF", League.NO_3),
    STROMMEN("Strømmen IF", League.NO_3),
    ULLENSAKER("Ullensaker/Kisa IL", League.NO_3),

    //TODO add clubs from NO_4 (84 clubs)
    TRAEFF("SK Træff", League.NO_4),

    MALMO("Malmö FF", League.SE_1),
    HACKEN("BK Häcken", League.SE_1),
    HAMMARBY("Hammarby IF", League.SE_1),
    ELFSBORG("IF Elfsborg", League.SE_1),
    DJURGARDEN("Djurgårdens IF", League.SE_1),
    AIK("AIK Solna", League.SE_1),
    GOTEBORG("IFK Göteborg", League.SE_1),
    NORRKOPING("IFK Norrköping", League.SE_1),
    SIRIUS("IK Sirius", League.SE_1),
    KALMAR("Kalmar FF", League.SE_1),
    BROMMA("IF Brommapojkarna", League.SE_1),
    HALMSTAD("Halmstads BK", League.SE_1),
    MJALLBY("Mjällby AIF", League.SE_1),
    VARNAMO("IFK Värnamo", League.SE_1),
    GAIS("GAIS", League.SE_1),
    VASTERAS("Västerås SK", League.SE_1),

    OSTERS("Östers IF", League.SE_2),
    VARBERGS("Varbergs BoIS", League.SE_2),
    TRELLEBORGS("Trelleborgs FF", League.SE_2),
    HELSINGBORG("Helsingborgs IF", League.SE_2),
    BRAGE("IK Brage", League.SE_2),
    DEGERFORS("Degerfors IF", League.SE_2),
    LANDSKRONA("Landskrona BoIS", League.SE_2),
    OSTERSUND("Östersunds FK", League.SE_2),
    SUNDSVALL("GIF Sundsvall", League.SE_2),
    UTSIKTEN("Utsiktens BK", League.SE_2),
    OREBRO("Örebro SK", League.SE_2),
    ORGRYTE("Örgryte IS", League.SE_2),
    GEFLE("Gefle IF", League.SE_2),
    SKOVDE("Skövde AIK", League.SE_2),
    SANDVIKEN("Sandvikens IF", League.SE_2),
    ODDEVOLD("IK Oddevold", League.SE_2),

    ESKILSTUNA("AFC Eskilstuna", League.SE_3_1),
    DALKURD("Dalkurd FF", League.SE_3_1),
    KARLSTAD("IF Karlstad", League.SE_3_1),
    LJUNGSKILE("Ljungskile SK", League.SE_3_2),
    BK_OLYMPIC("BK Olympic", League.SE_3_2),

    FUZINAR("NK Fuzinar", League.SI_1),

    NOVI_PAZAR("FK Novi Pazar", League.RS_1),
    VOZDOVAC("FK Vozdovac", League.RS_1),
    CUKARICKI("FK Cukaricki", League.RS_1),

    MACVA("FK Macva Sabac", League.RS_2),

    ALL_BOYS("CA All Boys", League.AR_2),

    PETROLERO("Club Independiente Petrolero", League.BO_1),

    INDY_ELEVEN("Indy Eleven", League.US_2);

    private final String name;
    private League league;

    Club(String name, League league) {
        this.name = name;
        this.league = league;
    }

    public List<Club> getByLeague(League league) {
        if (league == null) return null;

        List<Club> result = new ArrayList<>();
        for (Club c : Club.values()) {
            if (c.getLeague().equals(league)) {
                result.add(c);
            }
        }
        return result;
    }

    public Club getByEnumName(String enumName) {
        if (enumName == null || enumName.trim().isEmpty()) {
            return null;
        }

        for (Club c : Club.values()) {
            if (c.toString().equals(enumName)) {
                return c;
            }
        }

        return null;
    }

    public String getName() {
        return name;
    }

    public League getLeague() {
        return league;
    }

    public void setLeague(League league) {
        this.league = league;
    }
}
